Wip

diff --git a/prep b/prep
--- a/prep
+++ b/prep
@@ -1,8 +1,7 @@
 #!/bin/bash
 
-Checks=""
-defaultbranch="develop"
 
+# Private Functions
 __fail() {
     __test "FAIL: $1"  && exit 2
 }
@@ -12,11 +11,13 @@ __test() {
     echo -e "$1\n"
 }
 
+
+# Public Functions 
 pr() {
     cd $WORKDIR
     currentbranch=$(git branch | grep ^* | sed 's/^.* //g')
     branch="${2:-$currentbranch}"
-    read -p "Confirm, use $branch ?"
+    echo "Running as $(whoami)@${qasite} $(pwd)($branch) (and $qarepo for Algolia and DB)"
     clearc 
     git fetch && git checkout -fq $defaultbranch
     git pull
@@ -27,12 +28,11 @@ pr() {
         git merge -m "Merge $defaultbranch" $defaultbranch
     fi
     grep -r "<<<< HEAD" && __fail "Address conflicts" ||  __test "No conflicts"
-    (git ls-files --others --exclude-standard | egrep -v ".csv|.pem|.svg|cron/test.php") && __fail "Found unexpected local files (above)" || __test "No unexpected local files"
     CurrentBranch="$(git branch | grep '^*' | sed 's/^..//g')"
     [ "$CurrentBranch" == "$branch" ]  && __test "Successfully switched to $CurrentBranch" || __fail "Could not switch to $branch (currently $CurrentBranch)"
-    composer install --no-dev && __test "Updated composer" || __fail "Composer issues"
-    ./vendor/bin/phinx migrate -e ${qasite}
-    grunt dist
+    composer install --no-dev && __test "Updated composer" 2>/dev/null || __fail "Composer issues"
+    ./vendor/bin/phinx migrate -e $qarepo
+    grunt dist && __test "Executed grunt"
     echo -e "PASSED:\n$Checks"
 }
 
@@ -72,29 +72,21 @@ logs() {
 }
 
 
-mods() { # List files created or modified in last 60 mins
-     find . -cmin -60 -o -mmin -60
-}
-
-csv() { # Transpose a line from a CSV with it's header
-    [ -z "$rep" ] && export rep="./htdocs/reports/styleloungeCsDede.txt" 
-    [ -z "$val" ] && export val="98452"
-    paste -d'=' <(head -1 $rep | tr '|' '\n') <(cat $rep | grep $val | tr '|' '\n')
-    echo -e "\n\nUsed (export values to override)...\n\tval=$val \n\trep=$rep\n"
-}
-
-
- 
 help() {
     echo -e "\nUsage: $0 [Option]\n\nOptions;"
     declare -F | grep -v "__" | sed -e "s/^declare -f /\t/g" 
-    echo -e "\nWORKDIR: $WORKDIR\nSERVER.: $qasite\n"
+    echo -e "\nWORKDIR: $WORKDIR\nSERVER.: $qasite\nINDEXES: $qarepo"
 }
 
-[ -z "$WORKDIR" ] && __fail "WORKDIR not set"
-qasite=$(uname -n | sed "s/\...*//g")
-[ "$qasite" == "ip-10-90-0-249" ] && qasite="slaine"
-[ "$qasite" == "ip-10-90-0-53" ] && qasite="hammerstein"
-[ "$qasite" == "ip-10-90-0-18" ] && qasite="nemisis"
 
+# Declarations
+Checks=""
+: ${defaultbranch='develop'}
+: ${WORKDIR='/home/deploy/toska'}
+[ ! -f $WORKDIR/config.json ] && echo "Missing $WORKDIR/config.json" && exit 2
+qasite=$(cat /home/deploy/toska/config.json | egrep "website" | head -1 | sed -e 's/\..*, *$//g' -e 's/^..*"//g')
+qarepo=$(cat /home/deploy/toska/config.json | egrep "indexName" | head -1 | sed -e 's/_..*, *$//g' -e 's/^..*"//g')
+
+
+# Execution
 [ -z "$1" ] && help || eval $1 $@
